/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project_pust_face;

/**
 *
 * @author sr computer
 */
public class Waiver extends javax.swing.JFrame {

    /**
     * Creates new form Waiver
     */
    public Waiver() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        s9 = new javax.swing.JCheckBox();
        s10 = new javax.swing.JCheckBox();
        s11 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Waiver ");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Others Fees  : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 170, 50));

        s1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s1.setText("CSE");
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });
        jPanel1.add(s1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        s2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s2.setText("EEE");
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });
        jPanel1.add(s2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        s3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s3.setText("Civil");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel1.add(s3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        s4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s4.setText("BBA");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel1.add(s4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        s5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s5.setText("English");
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });
        jPanel1.add(s5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        s6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s6.setText("ISlamic Study");
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });
        jPanel1.add(s6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        s7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s7.setText("Public Health");
        jPanel1.add(s7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        s8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s8.setText("Physics");
        jPanel1.add(s8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        s9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s9.setText("Chemistry");
        jPanel1.add(s9, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        s10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s10.setText("Law");
        jPanel1.add(s10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 80, -1));

        s11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        s11.setText("Math");
        jPanel1.add(s11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Select a programm");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 240, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Details  for  this Program ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 320, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Tusion Fees : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 260, 50));

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 260, 50));

        jButton1.setBackground(java.awt.SystemColor.activeCaption);
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Back ");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 180, 50));

        jButton2.setBackground(java.awt.SystemColor.activeCaption);
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Your Waiver ");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 180, 50));

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Scholarship & Waiver ");

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 130));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Time/Years   : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 170, 50));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 260, 50));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 260, 50));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Total Credits  : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        if (s1.isSelected()) {
            String s1, s2;

            jTextField2.setText("125000");
            jTextField1.setText("156000");
            jTextField4.setText("158");
            jTextField3.setText("4 Years");
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("CSE");
            ss.jTextField2.setText("125000");
            ss.jTextField1.setText("156000");
            ss.setVisible(true);
        } else {
            jTextField2.setText(null);
            jTextField1.setText(null);
            jTextField4.setText(null);
            jTextField3.setText(null);
              Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s1ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        if (s2.isSelected()) {
            String s1, s2;

            jTextField2.setText("125000");
            jTextField1.setText("156000");
             jTextField4.setText("158");
            jTextField3.setText("4 Years");
             Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("EEE");
            ss.jTextField2.setText("125000");
            ss.jTextField1.setText("156000");
            ss.setVisible(true);
        } else {
            jTextField2.setText(null);
            jTextField1.setText(null);
             jTextField4.setText(null);
            jTextField3.setText(null);
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
        if (s3.isSelected()) {
            String s1, s2;

            jTextField2.setText("125000");
            jTextField1.setText("156000");
            jTextField4.setText("158");
            jTextField3.setText("4 Years");
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("Civil");
            ss.jTextField2.setText("125000");
            ss.jTextField1.setText("156000");
            ss.setVisible(true);
        } else {
            jTextField2.setText(null);
            jTextField1.setText(null);
            jTextField4.setText(null);
            jTextField3.setText(null);
             Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
        if(s4.isSelected())
        { 
            String  s1,s2; 
            
            jTextField2.setText("120000");
            jTextField1.setText("140000");
              jTextField4.setText("137");
            jTextField3.setText("4 Years");
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("BBA");
            ss.jTextField2.setText("120000");
            ss.jTextField1.setText("140000");
            ss.setVisible(true);
        }
        else
        { 
             jTextField2.setText(null);
            jTextField1.setText(null);
             jTextField4.setText(null);
            jTextField3.setText(null);
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s4ActionPerformed

    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        // TODO add your handling code here:
        if(s5.isSelected())
        { 
            String  s1,s2; 
            
            jTextField2.setText("125000");
            jTextField1.setText("94000");
             jTextField4.setText("132");
            jTextField3.setText("4 Years");
            Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("English");
            ss.jTextField2.setText("125000");
            ss.jTextField1.setText("94000");
            ss.setVisible(true);
        }
        else
        { 
             jTextField2.setText(null);
            jTextField1.setText(null);
            jTextField4.setText(null);
            jTextField3.setText(null);
             Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s5ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed
        // TODO add your handling code here:
        if(s6.isSelected())
        { 
            String  s1,s2; 
            
            jTextField2.setText("120000");
            jTextField1.setText("90000");
             jTextField4.setText("132");
            jTextField3.setText("4 Years");
              Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText("Islamic Study");
            ss.jTextField2.setText("120000");
            ss.jTextField1.setText("90000");
            ss.setVisible(true);
        }
        else
        { 
             jTextField2.setText(null);
            jTextField1.setText(null);
             jTextField4.setText(null);
            jTextField3.setText(null);
             Waiver_system ss=new Waiver_system(); 
            ss.jTextField3.setText(null);
            ss.jTextField2.setText(null);
            ss.jTextField1.setText(null);
            ss.setVisible(true);
        }
    }//GEN-LAST:event_s6ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        new  Waiver_system().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new Admission_information().setVisible(true);
        dispose(); 
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Waiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Waiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Waiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Waiver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Waiver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s10;
    private javax.swing.JCheckBox s11;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.JCheckBox s9;
    // End of variables declaration//GEN-END:variables
}
